### ISSUE TITLE
Loading gtlf with bayblone does not work

### ISSUE THREAD

**Issue by CLIcoder** [fenomas/noa#164]
BABYLON.SceneLoader.Append('./', 'Alien.gltf', scene, function (scene) {});

**Comment by fenomas** [comment]
Hi, when adding extra meshes to the scene make sure to call [noa.rendering.addmeshtoscene](https://fenomas.github.io/noa/API/classes/lib_rendering.rendering.html#addmeshtoscene). This adds your new mesh to the scene's octree.

If that's not the issue, then I'm afraid it's probably some kind of Babylon issue, which the folks in the Babylon forum may be able to help with.
