### ISSUE TITLE
Is there a way to draw on the gaming canvas

### ISSUE THREAD

**Issue by levlups** [fenomas/noa#170]
I tried to draw on the noa.container.canvas but it doesnt work ??? I cant get the context("2D") , any ideas???

**Comment by fenomas** [comment]
HTML canvas objects only do one mode - noa's is using `webgl`, so that's why trying to get a `2D` context returns null. If you want to draw 2D stuff on top of the 3D scene, that's probably something to ask in the [babylonJS forums](https://forum.babylonjs.com/) about?
