### ISSUE TITLE
voxels.index is undefined

### ISSUE THREAD

**Issue by itzTheMeow** [fenomas/noa#171]
When i try to call noa.world.setChunkData("id", data), i get this error:
![image](https://user-images.githubusercontent.com/50887230/145663604-cbf583e0-f0a5-4aa6-8118-d463ce6d8b2d.png)

I set up a primitive system to save/load the world on-demand:
```js
export function saveGame() {
  let loadedChunks = [
    noa.world._getChunkByCoords(0, 0, 0),
    noa.world._getChunkByCoords(32, 0, 0),
    noa.world._getChunkByCoords(0, 32, 0),
    noa.world._getChunkByCoords(0, 0, 32),
  ];
  let chunks = loadedChunks.map((c) => [c.requestID, c.voxels]);
  let crunched = chunks.map((c) => [
    c[0],
    c[1].data.length,
    { ...c[1], ...{ data: VoxelCrunch.encode(c[1].data) } },
  ]);

  localStorage.setItem("savegame", JSON.stringify(crunched));
}

export function loadGame() {
  let saveGameData = localStorage.getItem("savegame");
  if (!saveGameData) return;
  let chunks = JSON.parse(saveGameData);

  let uncrunched = chunks.map((c) => [
    c[0],
    {
      ...c[2],
      ...{
        data: VoxelCrunch.decode(
          new Uint8Array(Object.values(c[2].data)),
          new Uint16Array(c[1])
        ),
      },
    },
  ]);

  console.log(uncrunched);
}

```

sort of following #39
`worldDataNeeded` doesn't emit on block updates

i am calling `noa.world.setChunkData(id, Uint16Array)` from the uncrunched array. it seems to be encoding/decoding properly
![image](https://user-images.githubusercontent.com/50887230/145663633-75d36836-3864-4434-ac85-5dbfd1eea008.png)
index 0 being the chunk request ID, and index 1 being the .voxels data from _getChunkByCoords

this .index function does not seem to exist:
![image](https://user-images.githubusercontent.com/50887230/145663667-2029eb48-120a-4553-a4a9-6066e334e826.png)

**Comment by itzTheMeow** [comment]
my world is 64x64x64 from 0-64, which is why i'm only saving 4 chunks (which are size 32)
the remove chunk listener won't fire because the player doesn't move far enough away

**Comment by fenomas** [comment]
Hi, the issue here is that `noa.world.setChunkData` expects to receive an [ndarray](https://www.npmjs.com/package/ndarray) object, rather than a typed array. Ndarray is basically a wrapper around a typed array.

When noa requests a chunk of data it sends an empty ndarray, so the easiest approach is to un-crunch stored data into that:

```js
noa.world.on('worldDataNeeded', (id, array, x, y, z, worldName) => {
    var crunchedData = // data that was previously encoded
    VoxelCrunch.decode( crunchedData, array.data )
})
```
The naming is a bit confusing, but the `array` param in that handler is the empty ndarray, and `array.data` is the ndarray's internal typed array.

**Comment by itzTheMeow** [comment]
That works, and im able to save/load data now! Thanks.

Is there a way to load world data after the game has been loaded? (change the current world to something else)

**Comment by fenomas** [comment]
Yes, there are basically two modes for this. The default setup is, the engine sends you events when it needs data for a new chunk or when it's unloading data for an old chunk, and it manages the timing of these events automatically, based on each chunk's range from the player.

Alternately though, if you create noa with the `manuallyControlChunkLoading` flag, or you can dynamically set it as a [property](https://fenomas.github.io/noa/API/classes/noa_world.World.html#manuallyControlChunkLoading) on `noa.world`, then the engine will assume you're going to decide which chunks should be loaded or unloaded. Then you'll need to call [`manuallyLoadChunk`](https://fenomas.github.io/noa/API/classes/noa_world.World.html#manuallyLoadChunk) and `manuallyUnloadChunk` when you you (or your server) decides that a chunk is in or out of range.

After that though the flow is the same - when you tell the engine to load a chunk it will later (async) emit a request for data event, and you can then call `setChunkData`, etc. So the core logic is basically the same with both approaches, the only difference is whether you or the engine decides which chunks need to be loaded/reloaded/disposed.

**Comment by itzTheMeow** [comment]
noa.worldName should work, thanks
