### ISSUE TITLE
Andy sorry to bother how do I  save my map 

### ISSUE THREAD

**Issue by levlups** [fenomas/noa#66]
first when I go far from my initial chunk and come back , poof everything I built is gone ,
secondly cant save at all ,ca you give me some hints on were to start ,wich info should be saved and how to loaded when starting game , ill let you know of my discoveries .please this is a must

**Comment by andyhall** [comment]
Hi, this is written up in issue #39, hope that helps!

**Comment by levlups** [comment]
My dreams are crushed always wanted to make a voxel adventure , I cant even add this on the file
 var VoxelCrunch = require('voxel-crunch') it says module cant be found 
please andy help heres my file , give me a heads up 


I think the magic happens between 

function removeChunk( world, i, j, k ) {
  var id = getChunkID(i,j,k)  // world is the file that needs to be put in voxelcrunch or data storage 
  world._chunks[id].dispose()
  delete world._chunks[id]
  // alert the world
  world.emit( 'chunkRemoved', i, j, k )
}

and then 
function requestNewChunk( world, i, j, k ) {
  var id = getChunkID(i,j,k)
  var cs = world.chunkSize
  var chunk = new Chunk(world.noa, i, j, k, cs)
  world._chunks[id] = chunk
  var x = i*cs-1
  var y = j*cs-1
  var z = k*cs-1
//// here you look in data storage if it exist and you use that chunk if it exist 
  world.emit('worldDataNeeded', id, chunk.array, x, y, z)
}

please Andy can you modify my file and I will modify ,its the missing piece I need

**Comment by levlups** [comment]
[noa-testbed.zip](https://github.com/andyhall/noa/files/3537314/noa-testbed.zip)

**Comment by levlups** [comment]
modify the file and I will help you with anything on your github thanks

**Comment by andyhall** [comment]
Okay, so the short answer there is to do `npm install --save voxel-crunch` on the command line in your project folder, which will fix the error on the `require` statement. But the longer better answer is to read up a bit about how JS modules work - installing via `npm` and bundling via `webpack`. Good luck!

**Comment by EliteAsian123** [comment]
Hello are you still stuck on this? When I wanted to do this for my game it took a couple days to get it working. Assuming you figured out module error, here is my code:

```js
 // Make a variable for saving the data into
 var saveData = {};

// Ran when chunk is removed
noa.world.on('chunkBeingRemoved', function(id, array, userData) {
    // Encode the chunk data
    var encodedData = voxelCrunch.encode(array.data);
    // Save that to saveData
    saveData[id.toString()] = encodedData;
});

// Ran when chunk data is needed
noa.world.on("worldDataNeeded", function(id, data, x, y, z) {
    if (id.toString() in saveData) {
        // If the chunk data is found in saveData decode and pass the chunk data
	var decodedData = voxelCrunch.decode(saveData[id.toString()], new Uint32Array(data.data.length));
	data.data = decodedData;
    } else {
	// IMPORTANT! Chunk generation code
    }
	noa.world.setChunkData(id, data);	
});
```

Hope this works!

**Comment by levlups** [comment]
thanks ill try it

**Comment by levlups** [comment]
it failed says voxelCrunch.encode is not a function

is this part of code good=var voxelCrunch = require("voxel-crunch")

**Comment by levlups** [comment]
would you know how to do the same thing without using voxel crunch , no compression

**Comment by EliteAsian123** [comment]
Compression is highly recommended because ram will be quickly eaten up. But here is the code anyways:
```js
 // Make a variable for saving the data into
 var saveData = {};

// Ran when chunk is removed
noa.world.on('chunkBeingRemoved', function(id, array, userData) {
    // Save data to saveData
    saveData[id.toString()] = array.data;
});

// Ran when chunk data is needed
noa.world.on("worldDataNeeded", function(id, data, x, y, z) {
    if (id.toString() in saveData) {
        // If the chunk data is found in saveData and pass the chunk data
	data.data = saveData[id.toString()];
    } else {
	// IMPORTANT! Chunk generation code
    }
    // Pass chunk data
    noa.world.setChunkData(id, data);	
});
```

**Comment by levlups** [comment]
it worked without compression

**Comment by levlups** [comment]
question how can I add voxel crunch without using webpack

**Comment by levlups** [comment]
would you know a trick

**Comment by levlups** [comment]
sorry would you know waths causing this error 27 times :Uncaught TypeError: Cannot read property 'push' of null 

this part of the code bugs ,many times 

Chunk.prototype.initData = function() {
  // assuming data has been filled with block IDs, pack it with opacity/etc.
  var arr = this.array.data,
      len = arr.length,
      sol = this._solidLookup,
      op  = this._opaqueLookup,
      obj = this._objectMeshLookup
  var i, j, k
  for (i=0; i<len; ++i) {
    arr[i] = packID(arr[i], sol, op, obj)
  }
  this._terrainDirty = true

  // remake local view on assumption that data has changed
  this._unpaddedView = this.array.lo(1,1,1).hi(this.size,this.size,this.size)

  // do one scan through looking for object blocks (for later meshing)
  var view = this._unpaddedView
  var len0 = view.shape[0]
  var len1 = view.shape[1]
  var len2 = view.shape[2]
  var list = this._objMeshCoordList
  for (i=0; i<len0; ++i) {
    for (j=0; j<len1; ++j) {
      for (k=0; k<len2; ++k) {
        if (view.get(i,j,k) & OBJECT_BIT) {
		
						list.push(i,j,k)
		
        }
      }
    }
  }

  this.isGenerated = true
}

**Comment by EliteAsian123** [comment]
What code is this? Does this have anything to do with the issue?

**Comment by andyhall** [comment]
@levlups , it sounds like maybe you've pulled the `bundle.js` out of the old testbed demo and are editing it directly, without any build step. This is possible to do, but it's not the way the library is developed and I don't think any of us will be able to answer questions about doing things that way, since we cannot easily reproduce the environment.

E.g., the error you're currently seeing is from [here](https://github.com/andyhall/noa-testbed/blob/gh-pages/bundle.js#L4802), I guess, but object meshing has completely changed since then, so there's no comparable piece of code in the current version of noa.

The intended way to work with noa is to author JS modules and use webpack as a build tool to produce code bundles for a complete game. The process involves using [npm install](https://docs.npmjs.com/cli/install.html) to install local copies of dependency libraries, then authoring code with [require()](https://stackoverflow.com/questions/9901082/what-is-this-javascript-require) to get references to modules, and then use [webpack](https://webpack.js.org/concepts/) as a build tool to assemble the modules into a single working JS bundle.

It's a complicated process with a lot of moving parts, but if you follow the steps in the readme of the `noa-examples` repo you should be able to see it in action, as the relevant config files are already set up.

**Comment by levlups** [comment]
Sorry Andy and the others , my problen is when a JSON.strindify( ...compressed chunk ) and I save it on computer using fs ,when I loaded back and decompress it just gives me empty chunks any solution anyone

**Comment by fenomas** [comment]
Hi, there's no way to guess without more information. If you're getting empty chunks when restoring then probably `noa` is getting passed zeroes for voxel data, so perhaps there's some bug in how you're storing and retrieving the data?

Incidentally if you're using [voxel-crunch](https://github.com/mikolalysenko/voxel-crunch) to compress chunk data into typed arrays, it would probably be more efficient to stringify the data yourself instead of making it JSON:

```
var data = new Int8Array([1,2,3,4,5,6,7,8])
data.join(',')          //  '1,2,3,4,5,6,7,8'
JSON.stringify(data)    // '{"0":1,"1":2,"2":3,"3":4,"4":5,"5":6,"6":7,"7":8}'
```

**Comment by levlups** [comment]
hers my code 
const ndarray = require('ndarray')

var chunkList={}

var cruncher = require('voxel-crunch')
var hash = require('murmur-numbers')
var storage ={}//JSON.parse(localStorage.getItem('chunks'))//{}
var chunkIsStored = (id) => { return !!storage[id] }
var storeChunk = (id, arr) => { storage[id] = cruncher.encode(arr.data) }
var retrieveChunk = (id, arr) => { return cruncher.decode(storage[id], arr.data)}

storage=JSON.parse(localStorage.getItem('chunks'))
console.log(storage)
export function makeWorld(noa) {
	
	


// register for world events

    // catch engine's chunk removal event, and store the data
    noa.world.on('chunkBeingRemoved', function (id, array, userData) {
	
     storeChunk(id, array)
	   
	  
    })


  

    // catch worldgen requests, and queue them to handle asynchronously
    var requestQueue = []
    noa.world.on('worldDataNeeded', function (id, array, x, y, z, worldName) {
		
       // requestQueue.push({ id, array, x, y, z, worldName })
	  
	    if (chunkIsStored(id)) {
			retrieveChunk(id, array)
			//console.log('wath')
			//console.log(retrieveChunk(id, array))
		
		
		
		
		
        } else {
			
			
           generateChunk(id,array, x, y, z, worldName)
			
        }
		
		noa.world.setChunkData(id,array)
		
    })




 function generateChunk(id,array, x, y, z) {
	 var l=id.split("|")

	 var xoff = l[0]*24
		var zoff = l[2]*24
		var yoff = l[1]*24
        for (var i = 0; i < 24; ++i) {
			 for (var j = 0; j <24; ++j) {
                for (var k = 0; k < 24; ++k) {

								if ( (j+yoff) <45 ) {
								
						
						array.set(i,j,k,1)
								
								
								}
						
						
						}
					
                }
            }
			
			// storeChunk(id, array)
        }
}
	

	
	setTimeout(function(){ 

//localStorage.setItem('chunks',JSON.stringify(storage))
//console.log(storage)

	}, 10000);

**Comment by levlups** [comment]
if I console.log storage i get some decent data ???? i think 

if I console.log( retrieveChunk(id, array)) i get all zeros ????????  , im using localStorage to store the storage array as you see here
setTimeout(function(){ 
//localStorage.setItem('chunks',JSON.stringify(storage))
//console.log(storage)

}, 10000);

**Comment by levlups** [comment]
heres the solutio

    setInterval(function () {
        if (requestQueue.length === 0) return
        var req = requestQueue.shift()
		
		
        if (chunkIsStored(req.id)) {
			
			var k=storage[req.id]
			
			
			var l=[JSON.stringify(k)]



           storage[req.id]=Object.values(JSON.parse(l))
		
			
           retrieveChunk(req.id, req.array)
		
        } else {
			
			
           generateChunk(req.id,req.array, req.x, req.y, req.z, req.worldName)
			
        }
        // pass the finished data back to the game engine
		
        noa.world.setChunkData(req.id, req.array)
		
		
		
		/*if(!!storage[req.id]){
			return;
		}
		if(!!rtcblocklist[req.id]){
			
			
			for (const i in rtcblocklist[req.id]){
				
				noa.setBlock(rtcblocklist[req.id][i][0],rtcblocklist[req.id][i][1], rtcblocklist[req.id][i][2], rtcblocklist[req.id][i][3])
			}
		
		}*/
		
    }, 10)

**Comment by fenomas** [comment]
Cool, glad it worked!
